name: CollaborationBoostsCareer
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=3.6
  - r-tidyverse
  - r-mvtnorm
  - r-knitr
  - r-rmarkdown
  - r-devtools
  - r-rcpp
  - r-coda
  - r-ggplot2
  - r-bibliometrix
  - r-rscopus
  - r-jtools
  - r-rowr
